name: Update Proxy List Every 15 Minutes

on:
  schedule:
    # Запускаем каждые 15 минут
    - cron: '*/15 * * * *'

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt  # Должен содержать pysocks, bs4, requests
      - name: Run proxy scraper
        run: |
          source .venv/bin/activate
          python proxy_scraper.py
